# Generated by Django 2.2.5 on 2019-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='air_conditioner',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='bridal_room',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='decoration',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='dj_system',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='generator',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='heater',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='outside_catering',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='outside_decoration',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='outside_dj',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='valet_parking',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='wifi',
            field=models.BooleanField(),
        ),
    ]
