# Generated by Django 2.2.5 on 2019-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20191018_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('Banquet Hall', 'Banquet Hall'), ('Marquee', 'Marquee'), ('Hotel Hall', 'Hotel Hall'), ('Farmhouse', 'Farmhouse'), ('Lawn', 'Lawn')], default='Banquet Hall', max_length=50),
        ),
    ]
