# Generated by Django 2.2.5 on 2019-10-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20191003_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='min_guest',
        ),
    ]
