# Generated by Django 2.2.5 on 2019-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_venue_min_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=3),
        ),
        migrations.AlterField(
            model_name='detail',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
